### ISSUE TITLE
Hover the button on sidebar

### ISSUE THREAD

**Issue by thomasbnt** [thepracticaldev/dev.to#1672]
**Describe the bug**
The hover of the button in the sidebar is a little under pressure .

[Link to the post of example](https://dev.to/devteam/the-7-most-popular-dev-posts-from-the-past-week-4kn7)

**To Reproduce**
Hover the button.

**Expected behavior**
No bug with the focus and hover.

**Screenshots**
![bug_css_devto_28012019](https://user-images.githubusercontent.com/14293805/51863078-6328ad00-2340-11e9-8666-61bf9f757861.gif)

**Desktop (please complete the following information):**

- OS: **Ubuntu 16.04**
- Browser : Chrome 
- Version : **Version 71.0.3578.98 (Official Build) (64 bits)**

**Comment by rhymes** [comment]
info for who might take this one: doesn't happen on Firefox 65 in macOS

![button](https://user-images.githubusercontent.com/146201/51864028-db906d80-2342-11e9-8487-3f13ab6bacf2.gif)

**Comment by Link2Twenty** [comment]
As a general rule animating margin and padding is a bad idea.

This code is causing the problem.
https://github.com/thepracticaldev/dev.to/blob/9ea53d5669ce17b105aa5adc39f4a6871bdafd3a/app/assets/stylesheets/sticky-nav.scss#L167-L189

I would propose this change
```scss
a.primary-sticky-nav-org-cta-link{
  display: inline-block;
  font-size:1.25em;
  border:0px;
  border-radius:100px;
  padding: 6px 38px;
  margin-top: 20px;
  background: white;
  color: $black;
  font-family: $helvetica-condensed;
  font-weight: bold;
  text-align: center;
  font-stretch: condensed;
  box-shadow: $light-shadow;
  margin-bottom: 5px;
  transform: scale(0.99) translateY(0px);
  transition: transform 150ms cubic-bezier(0.4, 0.0, 0.2, 1);
  &:hover {
    box-shadow: $dark-shadow;
    transform: scale(1) translateY(-1px);
  }
}
```

![animate_contrib](https://user-images.githubusercontent.com/3534427/51895611-7b311880-23a2-11e9-8c05-120abd8169d1.gif)
