### ISSUE TITLE
dark mode - code in comments needs contrast

### ISSUE THREAD

**Issue by johnpapa** [thepracticaldev/dev.to#2210]
see below

![image](https://user-images.githubusercontent.com/1202528/54965579-82f6de80-4f47-11e9-9231-c80a91e778f6.png)

**Comment by ashToronto** [comment]
I was able to replicate the problem in my environment, am working on solving it. 
<img width="846" alt="Screen Shot 2019-04-12 at 12 24 23 PM" src="https://user-images.githubusercontent.com/33923739/56051973-4c2e1000-5d1e-11e9-8fcb-f97a10e36bf6.png">

**Comment by ashToronto** [comment]
While I was investigating, I found out that the night mode uses the invert functionality to switch colors but the backtick code uses a default theme color. We need to make a new variable for the markdown inline code so that it has better contrast.  

```scss
body.night-theme {
  .on-page-nav-butt img, .icon-img, .dropdown-icon, .reaction-button:not(.reacted) img, .image-upload-button button, .icon-image {
    -webkit-filter: invert(95%);
    filter: invert(95%);
  }
}
```

**Comment by ashToronto** [comment]
Added a specific override for the night-theme css variable. 

```scss 
$night-theme-markdown-inline-code: #ffffff;

body.night-theme {
  .on-page-nav-butt img, .icon-img, .dropdown-icon, .reaction-button:not(.reacted) img, .image-upload-button button, .icon-image {
    -webkit-filter: invert(95%);
    filter: invert(95%);
  }
  .inner-comment code {
    color: $night-theme-markdown-inline-code;
  }
}

```

<img width="846" alt="Screen Shot 2019-04-12 at 12 46 46 PM" src="https://user-images.githubusercontent.com/33923739/56053076-16d6f180-5d21-11e9-9fe2-888fe22250eb.png">
