### ISSUE TITLE
Consider using a SASS mixin for themeable style

### ISSUE THREAD

**Issue by nickytonline** [thepracticaldev/dev.to#2539]
**Is your feature request related to a problem? Please describe.**
Not a user problem, but more of a suggestion for a better developer experience. [Fallbacks can be forgotten](https://github.com/thepracticaldev/dev.to/pull/2538#discussion_r277981949) and no one likes typing more than they have to. 😉

Currently if adding themeable styling, you write it like so

```sass
  box-shadow: $bold-shadow; /* the fallback */
  box-shadow: var(--theme-container-box-shadow, $bold-shadow); /* modern css */
```

**Describe the solution you'd like**
Consider using a SASS mixin to handle themeable style.

```sass
@mixin themeable(
  $property,
  $cssVariable,
  $fallback) {

  #{$property}: #{$fallback};
  #{$property}: var(--#{$cssVariable}, #{$fallback});
}

.some-class {
 @include themeable(box-shadow, theme-container-box-shadow, $bold-shadow)
}
```

would generate

```css
.some-class {
  box-shadow: $bold-shadow;
  box-shadow: var(--theme-container-box-shadow, $bold-shadow);
}
```

**Describe alternatives you've considered**
N/A
