### ISSUE TITLE
Style suggestions

### ISSUE THREAD

**Issue by ramlmn** [thepracticaldev/dev.to#32]
Since you are trying to use fonts like 'Helvetica' and 'Arial' which are quite local, I think that its better to use something like the following for global text, emoji support and better look like native, similar to github...
``` css
html,
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    "Helvetica Neue", Helvetica, Arial, sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
}
```

...and specifying local monospaced fonts for footer and code like:
``` css
pre, code {
  font-family: Consolas, Menlo, Monaco, 'Droid Sans Mono',
    'Source Code Pro', 'DejaVu Sans Mono', 'Ubuntu Mono',
    Courier, monospace;
}
```

Hope you like it 🙂

**Comment by ramlmn** [comment]
Also consider adding:
``` css
*,
*::before,
*::after {
  box-sizing: border-box;
}
```
which obviously breaks most of the current sites' layout.
