### ISSUE TITLE
Yaml code block not rendered correctly

### ISSUE THREAD

**Issue by Kovah** [thepracticaldev/dev.to#3712]
**Describe the bug**

For some unknow reason, a simple Yaml code block is not rendered correctly in my [latest post](https://dev.to/kovah/cut-your-docker-for-mac-response-times-in-half-with-docker-sync-1e8j). The code block is standalone, not surrounded by other elements like lists.

**To Reproduce**

The following markdown works very well with all other markdown generators but breaks itself and all following code blocks on dev.to:

    ```yml
    version: "2"
    services:
    
      php:
        volumes:
          - your-app-files:/app:nocopy
    
      nginx:
        volumes:
          - your-app-files:/app:nocopy
    
    volumes:
      your-app-files:
        external: true
    ```

**Expected behavior**

I expect the rendered page to render the Yaml code block correctly and apply syntax highlighting.

**Screenshots**

This is the actual result generated by the dev.to site:

![Screenshot 2019-08-13](https://user-images.githubusercontent.com/1816101/62972225-d93fbd80-be13-11e9-895e-f58a7d1dc66e.jpg)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Firefox
- Version: 68

**Additional context**

The same Yaml works well by using indented code blocks like this, but syntax highlighting is then gone:

        version: "2"
        services:
        
          php:
            volumes:
              - your-app-files:/app:nocopy
        
          nginx:
            volumes:
              - your-app-files:/app:nocopy
        
        volumes:
          your-app-files:
            external: true
