### ISSUE TITLE
Add some visual difference for hovered state of comments counter

### ISSUE THREAD

**Issue by Defman21** [thepracticaldev/dev.to#656]
## Feature Request or Task

Add some visual difference for hovered state of comments counter.

### User Story / Description

Since you've implemented #207, I hovered on the comments counter and it wasn't obvious that something will happen if I click on it. My browser showed me an URL in left bottom corner of my window that this counter now jumps to comments though.

### Definition of Done

Some background or anything that will have visual difference with the base state.

![image](https://user-images.githubusercontent.com/7100645/45534983-8f1a1a80-b805-11e8-9c2b-7f932c0d86f4.png)

**Comment by Defman21** [comment]
un-stale.

**Comment by jessleenyc** [comment]
Yeah, this makes a lot of sense @Defman21. This is approved for anyone who wants to work on it.

**Comment by omenking** [comment]
A simple request but more here than you'd expect.
See how there are two comment icons.
Both do not have the same selectors so before this can be applied there needs to be standardization on wherever it is used. A quick search of the image names should make it easy to determine where all these elements used

<img width="714" alt="Screen Shot 2019-04-09 at 5 25 39 PM" src="https://user-images.githubusercontent.com/7776/55836446-8617d000-5aec-11e9-9888-2bd1380ce03c.png">

**Comment by omenking** [comment]
So here I applied a bit of opactiy to the images

<img width="183" alt="Screen Shot 2019-04-09 at 5 51 07 PM" src="https://user-images.githubusercontent.com/7776/55837693-1e638400-5af0-11e9-9d48-bf1b0f44c6a4.png">

Here is the hover with the opacity at 100% and I made the text black.
<img width="188" alt="Screen Shot 2019-04-09 at 5 51 10 PM" src="https://user-images.githubusercontent.com/7776/55837704-27ecec00-5af0-11e9-86d7-8c39f0c4742f.png">

I am aware of other hover effects that use a grey background but though a subtle approach worked best here but I can change accordingly.

In the `articles.scss` here you can see my changes:
```scss
      &.comments-count {
        left: 93px;
        img {
          opacity: 0.8;
          width: 28px;
        }
        &:hover {
          a {
            color: rgb(0,0,0);
          }
          img {
            opacity: 1;
          }
        }
      }
      &.reactions-count {
        left: 20px;
        img {
          opacity: 0.8;
        }
        &:hover {
          a {
            color: rgb(0,0,0);
          }
          img {
            opacity: 1;
          }
        }
      }
```
