### ISSUE TITLE
Loses tags

### ISSUE THREAD

**Issue by JoshCheek** [thepracticaldev/dev.to#8]
I set my front matter to this, note that there are 6 tags:

```yaml
---
title:       Write a REPL in Ruby
published:   true
description: Lets build a REPL!
cover_image: 
tags:        pry,irb,repl,ruby,console,terminal
---
```

---

It loses the last three tags:

![screenshot 2016-12-13 12 02 57](https://cloud.githubusercontent.com/assets/77495/21152524/2c3cca10-c12c-11e6-84a3-c91cd73b77c9.png)

---

The post is not linked under the lost tags (it is linked under the ones displayed above):

![screenshot 2016-12-13 12 04 19](https://cloud.githubusercontent.com/assets/77495/21152561/698794b8-c12c-11e6-9d0c-c04761d73fac.png)
