### ISSUE TITLE
Footer is pushed down due to infinite scroll...but I'd like to read it.

### ISSUE THREAD

**Issue by davidjeddy** [thepracticaldev/dev.to#806]
## Feature Request or Task
Disable infinite scrolling at the bottom of the landing page in hopes of being able to read / interact with the footer UI.

### User Story / Description
I'd like to interact with the links or read the contents of the footer on the landing page when scrolled to the bottom of the page.

### Definition of Done
Ability to interact with the links in the footer of the landing page.

**Comment by nektro** [comment]
All of the info in the footer is also in the "key links" block of the left side bar
![image](https://user-images.githubusercontent.com/5464072/46453149-f45e8d00-c76d-11e8-96cf-4a17f42586a7.png)

**Comment by Link2Twenty** [comment]
It's true that all the links are on the side, but if you did want the footer to be sticky on infinite scrolling pages you could change the CSS to something like this.

```css
footer {
    position: fixed;
    bottom: 0;
    left: 50%;
    transform: translateX(-50%);
    z-index: 10;
}
```
